apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example
  description: example.com
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: backstage/backstage
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
