apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example
  description: example.com
  annotations:
    backstage.io/techdocs-ref: dir:.
  # links:
  # - url: https://github.com/itisaby
  #   title: My Dashboard
  #   icon: dashboard
    # github.com/project-slug: itisaby/DevPro
    # github.com/project-slug: backstage/backstage
spec:
  type: website
  lifecycle: unknown
  owner: guests
