apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backendfirst2
  links:
    - url: https://github.com/itisaby/Backstage-First/tree/main
      title: My Dashboard
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: guests
  dependsOn:
    - component:default/DevPro
    - component:default/DevWorld
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DevPro
  links:
    - url: https://github.com/itisaby
      title: My Dashboard
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: itisaby/DevPro
    github.com/project-readme-path: README.md
spec:
  type: other
  lifecycle: unknown
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DevWorld
  links:
    - url: https://github.com/itisaby
      title: My Dashboard
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: itisaby/DevPro
    github.com/project-readme-path: README.md
spec:
  type: other
  lifecycle: unknown
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ortelius-www
  description: Ortelius Website
  annotations:
    github.com/project-slug: ortelius/ortelius-docs
    github.com/project-readme-path: README.md
    # argocd/app-name: ortelius-www
    backstage.io/kubernetes-id: ortelius-www
    backstage.io/techdocs-ref: dir:.
  tags:
    - platform
spec:
  type: service
  owner: user:guest
  system: Platform
  lifecycle: production
  dependsOn:
    - component:default/backstagefirst2
