apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example
  description: example.com
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/itisaby/Backstage-First/tree/main # Path to the directory containing mkdocs.yml
spec:
  type: other
  lifecycle: unknown
  owner: guests