apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backendfirst2
  links:
    - url: https://github.com/itisaby/Backstage-First/tree/main
      title: My Dashboard
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: experimental
  owner: guests
  dependsOn:
    - component:default/DevPro
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DevPro
  links:
    - url: https://github.com/itisaby
      title: My Dashboard
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: itisaby/DevPro
    github.com/project-readme-path: README.md
spec:
  type: other
  lifecycle: unknown
  owner: guests
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DevWorld
  links:
    - url: https://github.com/itisaby
      title: My Dashboard
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: itisaby/DevPro
    github.com/project-readme-path: README.md
spec:
  type: other
  lifecycle: unknown
  owner: guests
